### ISSUE TITLE
Status 404 for Windows Installation Instruction

### ISSUE THREAD

**Issue by ramlaxman** [plone/Installers-UnifiedInstaller#113]
On plone.org website, it is directed at [wrong location](https://github.com/plone/Installers-UnifiedInstaller/blob/windows_install/docs/windows.rst) whereas here is the [correct location](https://github.com/plone/Installers-UnifiedInstaller/blob/master/docs/windows.rst). Please update on website to avoid confusion for beginners.

**Comment by mauritsvanrees** [comment]
I fixed that link a while ago in the [5.2.4](https://plone.org/download/releases/5.2.4) release.

Where did you find this wrong link then? Ah, the latest [4.3 release](https://plone.org/download/releases/4.3.20) has it too. Fixed there as well now. Well, I let it point to [an earlier version](https://github.com/plone/Installers-UnifiedInstaller/blob/935bfdc72850dfa95bf202f1c0a0fd9c666f478c/docs/windows.rst) otherwise readers will start to install Python 3, which is not usable on 4.3. The earlier version talks about Plone 5.1 instead of 4.3, but this was the earliest Windows documentation that I could find.

Thanks.
