### ISSUE TITLE
Finished install, the theme css seem did not  work

### ISSUE THREAD

**Issue by maniachhz** [plone/Installers-UnifiedInstaller#49]
Dear all,

Finished install,  started the plonectl
```
gecko@debian:/opt/plone/zinstance$ sudo bin/plonectl fg
instance: 2016-01-02 17:33:19 INFO ZServer HTTP server started at Sat Jan  2 17:33:19 2016
	Hostname: 0.0.0.0
	Port: 8080
2016-01-02 17:33:19 INFO Zope Set effective user to "plone_daemon"
2016-01-02 17:33:22 INFO DocFinderTab Applied patch version 1.0.5.
2016-01-02 17:33:22 WARNING ZODB.blob (10292) Blob dir /opt/plone/zinstance/var/blobstorage/ has insecure mode setting
/opt/plone/buildout-cache/eggs/plone.app.multilingual-3.0.12-py2.7.egg/plone/app/multilingual/browser/migrator.py:11: DeprecationWarning: LanguageRootFolder: LanguageRootFolders should be migrate to DexterityContainers
  from plone.app.multilingual.content.lrf import LanguageRootFolder
2016-01-02 17:33:27 INFO Plone OpenID system packages not installed, OpenID support not available
2016-01-02 17:33:31 INFO Zope Ready to handle requests
2016-01-02 17:34:08 INFO plone.app.theming.policy local cache invalidated on thread 140662742025984
2016-01-02 17:34:08 INFO plone.app.theming.policy initializing local cache on thread 140662742025984 for http://127.0.0.1:8080/test_2::barceloneta
/opt/plone/buildout-cache/eggs/five.pt-2.2.3-py2.7.egg/five/pt/expressions.py:161: DeprecationWarning: showEditableBorder is renamed to showToolbar
  return base()
```
I open the URL, the GUI shows  below,  the theme css seem didn't  workt:
![screenshot from 2016-01-02 17 51 12](https://cloud.githubusercontent.com/assets/9192796/12074048/858129c2-b179-11e5-9193-f6c56c3ea891.png)

Any sugguestions?  Thanks.

**Comment by polyester** [comment]
hi @maniachhz , these kind of questions are better asked at https://community.plone.org, only bugs should go in here. 

As for your specific question, by default '127.0.0.1' is in the theme setup as 'unthemed host names'. That is by design, it is a sort of safeguard to see if you can reach the site if you have somehow messed up the theming.

If you visit your site at 'localhost' instead of '127.0.0.1' you should see the theming applied.

**Comment by maniachhz** [comment]
@polyester, 
thanks.
BTW, maybe it's better to add above info to Installation instructions for the beginner.

**Comment by svx** [comment]
Just as a site note, this is already updated in the installer docs [17 October 2015], but not yet on docs.plone.org.

https://github.com/plone/Installers-UnifiedInstaller/blob/master/docs/index.rst

I guess the reason is, that the plan was/is to include the installer docs to docs.plone.org what not yet happened.
