### ISSUE TITLE
update messages.sh

### ISSUE THREAD

**Issue by gnafou** [plone/Installers-UnifiedInstaller#57]
line 160 :  in debian8 the name of the lib is updated :  (Debian/Ubuntu zlibg-dev)  becomes  (Debian/Ubuntu zlib1g-dev)

**Comment by gforcada** [comment]
@gnafou would you  mind creating a pull request for that? Thanks in advance!!

**Comment by svx** [comment]
Question, is it possible to make this a bit more clear as in which versions of Debian and Ubuntu exactly ?

Meaning is that meant for Ubuntu:
- 14.04 ?
- 16.04 ?

Since package names may differ, like this whole issue here is about, we should make sure that user are able to find the right name of the package according to their version.

For this we should explicit name/mention the right package name for the version, otherwise people who are using 14.04 will search for the wrong package (only 16.04, for example)

**Comment by jensens** [comment]
Probably outdated. Reopen if I am wrong.
